### ISSUE TITLE
Click events not working reliably with window resize & scrolling

### ISSUE THREAD

**Issue by sebastiangraz** [splinetool/react-spline#101]
Using the latest versions and I'm having issues with click events not firing. Might be related to this issue https://github.com/splinetool/react-spline/issues/86. 

How to repro:
- Scroll down,
- Resize window couple of times
- Attempt to click to toggle state

Sometimes it works, sometimes it doesn't. Fails 40% of the time. Seems the "hitbox" of the element doesn't sync with the position of the 3D element in the DOM.

React Sandbox:
https://uwg187.csb.app/

Spline file:
https://app.spline.design/file/30c48d7b-52a5-4f82-838e-7762567527ae

Settings:
![image](https://user-images.githubusercontent.com/305057/206911345-88ad313f-5950-4113-9256-08eb809c5a81.png)

Versions:
```
"@splinetool/react-spline": "^2.2.5",
"@splinetool/runtime": "^0.9.153",
```

Gif of bug: 
https://cdn.discordapp.com/attachments/936730866896502834/1033777594753097808/bug.gif

**Comment by marcofugaro** [comment]
Hey, I am not able to reproduce, can you show with a gif how to reproduce it on the codesandbox you provided?

**Comment by sebastiangraz** [comment]
Sure, using the above sandbox:

https://user-images.githubusercontent.com/305057/207028142-f0b6f62e-22b3-419f-8fd1-0692837b7102.mov

**Comment by marcofugaro** [comment]
This has been fixed.
