### ISSUE TITLE
Render issue with @splinetool/runtime

### ISSUE THREAD

**Issue by grahamd711** [splinetool/react-spline#106]
Hello! Thanks for the great work on this project. We recently have run into issues with newer version of @splinetool/runtime. Using versions v0.9.154 or higher causes the scene to not render at all. Previously, we have no issues rendering Spline scenes using React-Spline and Spline Runtime.

Below are reproductions of working and broken demos:

https://codesandbox.io/s/frosty-breeze-t8gtep?file=/package.json  (broken)

https://codesandbox.io/s/thirsty-gwen-fn4y9z?file=/package.json (working)

We are having to pin the NPM package to v0.9.154 or lower to prevent this from happening on our already live production app.

```
Node - 16.18.1
NPM - 8.19.2
React - 17.0.2
React Dom - 17.0.2
```

**Comment by grahamd711** [comment]
@marcofugaro  thanks for the fast response. In the example you provided (https://codesandbox.io/s/xdvjw1?file=/package.json) , the scene does not animate.

we can try a new export and URL, but trying to understand what caused the issue to begin with. we are using the Spline scene on the homepage of a production app, so ideally we would not ever need to change the export URL. nothing has been changed in the scene itself, so trying to find out what stopped working with newer runtime versions.

**Comment by marcofugaro** [comment]
> @marcofugaro thanks for the fast response. In the example you provided (https://codesandbox.io/s/xdvjw1?file=/package.json) , the scene does not animate.

@grahamd711 the file in the library doesn't have any animation.

> we can try a new export and URL, but trying to understand what caused the issue to begin with. we are using the Spline scene on the homepage of a production app, so ideally we would not ever need to change the export URL. nothing has been changed in the scene itself, so trying to find out what stopped working with newer runtime versions.

ok, if you don't need to export again, you can just lock the `@splinetool/runtime` version and don't upgrade it again.

**Comment by grahamd711** [comment]
ok, understood. thanks for feedback @marcofugaro!
