### ISSUE TITLE
compatibility with all browsers?

### ISSUE THREAD

**Issue by MelanieCroce** [splinetool/react-spline#111]
Hello ! 

I have no problem with recent browsers, I would like to know the compatibility with old browsers because my colleague who has an old version of Safari (version 14.1.2) does not see the same thing as me.

What I see / what he sees, a picture is missing.

<img width="702" alt="Capture d’écran 2023-01-24 à 14 21 57" src="https://user-images.githubusercontent.com/14973984/214305852-f8da1d97-2658-4c93-94c8-dae3b6042498.png">

**Comment by marcofugaro** [comment]
Spline supports [all modern browsers which support Webgl2](https://caniuse.com/webgl2), supporting Safari 14.1.2 is not planned.
