### ISSUE TITLE
[Feature Request] Ability to modify text

### ISSUE THREAD

**Issue by fluid-design-io** [splinetool/react-spline#113]
Hello!

This is an amazing tool ✨ and I wonder if it's possible to add an additional feature to modify the text using the `findObjectByName` or `findObjectById`? 

For example:
```jsx
function onLoad(spline) {
    const obj = spline.findObjectByName('Text');
    // change the content of the text
    obj.text('Something Else')
    // or 
    obj.text = "Something Else"
  }
```
Appreciate your help!!

**Comment by marcofugaro** [comment]
Not possible at the moment, but we'll look into it!

**Comment by natapg** [comment]
this would be great!!

**Comment by MuLoo** [comment]
I look forward to this feature being launched soon. 
BTW, there has been no updated version for a long time.

**Comment by superguigui** [comment]
Hi this is now possible using string variables in your spline scene and modifying the variable through the runtime API `spline.setVariable('myStringVariable', 'new text')`.
The `spline` object is exposed as an argument of the `onLoad` prop function of `react-spline.` Happy coding !
