### ISSUE TITLE
Mouse Hover Events not resetting when used in React

### ISSUE THREAD

**Issue by Suvraneel** [splinetool/react-spline#118]
@marcofugaro @splinetool
This bug is pretty recent I'm guessing.
So, my scene is misbehaving on my React website. 
**As you can see on my website, if you hover over objects they respond but lag and stay that way even after `onMouseLeave`**

### My React website deployment:  https://suvraneel-folio-d6x5980g1-suvraneel.vercel.app/

It works perfectly fine on the Public URL (1st link) but not when used (2nd link)

**Comment by Suvraneel** [comment]
Update: I don't know how but it started working today.
Current production deployment: https://suvraneel.software

Hence, closing this issue.

**Comment by dharmeshds** [comment]
I am facing the same issue.. I am changing the cursor for some objects which are links from my nextjs app using @splinetool/runtime and the cursor remains changed even after I move the mouse away from those objects.

` splineApp.addEventListener('mouseHover', (e: any) => {
      if (['sudioLogo', 'subscribeButton', 'privacyPolicy', 'termsOfUse', 'cookiePolicy'].indexOf(e?.target?.name) > -1) {
        document.body.style.cursor = 'pointer';
      }
    });`
