### ISSUE TITLE
mouseHover

### ISSUE THREAD

**Issue by DamirKaramustafic** [splinetool/react-spline#120]
Hi there,

One question. How to track mouse out/mouse leave events? I need to do something when the mouse leaves the object? 

Thanks for help.

**Comment by wholelott4** [comment]
```
<Spline
        onMouseLeave={() => console.log('Mouse out')}
        scene="https://prod.spline.design/Vco6aLQFoV7ZvEQL/scene.splinecode"
        onLoad={onLoad}
/>
```

**Comment by superguigui** [comment]
If what you want to do is check the mouse leave of the canvas element then @wholelott4's answer is the way to go.
If you want to check the mouse leave of one of the 3d object of the scene then it's a little trickier as there's no mouseLeave event in Spline. You can try and use the `Mouse Hover` event from the editor though.
