### ISSUE TITLE
Provide access to object states

### ISSUE THREAD

**Issue by vanceingalls** [splinetool/react-spline#123]
I can see that the object states are available in the objects in the Application instance, but no access is provided to them through the SDK. The documentation suggests managing state transitions by triggering events, but I have a situation where spline events don't map to the events triggering state transitions in my app. Right now, I'm copy-pasting the state from the spline app into my app and referencing that to make my state transitions. Would it be possible to provide read access to these object states in the SDK in addition to the events? Thanks!

**Comment by zj1024** [comment]
@vanceingalls hi, I had the same problem. I'm also going to copy the data

but how to use in react spline. The data structure does not match in three js animation track

![image](https://user-images.githubusercontent.com/34162213/233536436-ae392f68-19ea-4d18-9160-c2f6484de098.png)

**Comment by 6174** [comment]
Need the same feature for my customize animation control , @vanceingalls  how to make animation from different states?

**Comment by superguigui** [comment]
Hi, for various reasons we want to avoid exposing the actual state data of the object.
However with the new variables API it's possible to do what you ask by:
- in editor create a new variable (could be a string)
- on the object you want to animate add a Variable change event, and assign it a conditional action that checks the value of your variable 
<img width="268" alt="image" src="https://github.com/splinetool/react-spline/assets/400119/95c8f63f-3021-4223-972a-2d484dadd61b">

I hope that helps!
