### ISSUE TITLE
Next.js Refused to load the image 'blob:http://localhost:3000/...' because it violates the following Content Security Policy directive: "img-src 'self' data:".

### ISSUE THREAD

**Issue by josegutierro** [splinetool/react-spline#129]
Hello,

I'm getting the following error on Next.js 12.1 with @splinetool/react-spline 2.2.6 and @splinetool/runtime 0.9.300

`Refused to load the image 'blob:http://localhost:3000/5804f024-b6ce-401d-ab20-7c58fb5e3d39' because it violates the following Content Security Policy directive: "img-src 'self' data:".
`

Thank you.

**Comment by alex-streza** [comment]
Hi there, I couldn't reproduce this error, would you mind providing a CodeSandbox showcasing that bug?

Also are you certain you're using the right URL for the scene you're trying to render?

I'm not certain of the error cause but this [SoF](https://stackoverflow.com/questions/40360109/content-security-policy-img-src-self-data) may help (I know you may have also done this search yourself)

**Comment by marcofugaro** [comment]
Can't reproduce the error, might be caused by weird configuration. Please provide a CodeSandbox with the error and we can reopen the issue.
