### ISSUE TITLE
The Spline Runtime only accepts .splinecode files that are generated from Spline export panel.

### ISSUE THREAD

**Issue by NewEue** [splinetool/react-spline#132]
![image](https://github.com/splinetool/react-spline/assets/17906785/997fa6c8-b5bf-4694-a2b8-37602e97b363)

**Comment by marcofugaro** [comment]
Yeah, you can't use `.spline` files with react-spline. Please use the `.splinecode` available at this link

<img width="458" alt="image" src="https://github.com/splinetool/react-spline/assets/7217420/5834d73b-3574-47d7-b7a9-632e1af296d0">
