### ISSUE TITLE
Weird responsive scene when resizing/refreshing screen

### ISSUE THREAD

**Issue by wholelott4** [splinetool/react-spline#137]
When I load the website on a desktop size and resize it to the minimum I can (to simulate a mobile, for example), the scene looks fine. But If I refresh the website using the minimum size I can (simulating a mobile again), the scene becomes all cut.

This is when I load the website using a desktop size and resize it to the minimum I can: (Simulating a mobile)
<img width="491" alt="Captura de Tela 2023-06-19 às 16 38 00" src="https://github.com/splinetool/react-spline/assets/104055115/bf382a08-7373-4de2-934e-6be1df267f63">

When I am with the mininum size I can, if I refresh the website, the scene becomes this:
<img width="495" alt="Captura de Tela 2023-06-19 às 16 38 26" src="https://github.com/splinetool/react-spline/assets/104055115/27144f7b-4b08-44cd-909b-dce46842ea1a">

Why is it happening?

**Comment by marcofugaro** [comment]
Hi, can you share the website in question?

**Comment by wholelott4** [comment]
> Hi, can you share the website in question?

It suddenly stopped happening. Not sure what happened at all.
