### ISSUE TITLE
Add lookat event listener for whole window

### ISSUE THREAD

**Issue by OpGammer11** [splinetool/react-spline#145]

**Comment by HoangKimDuc** [comment]
is there any progress?

**Comment by superguigui** [comment]
Hi there's an API on Spline runtime library to do just that:
`spline.setGlobalEvents(true);`

the way to access the spline object in react-splline is through the `onLoad` prop.
Ex:

`<Spline onLoad={(spline) => spline.setGlobalEvent(true)} scene={...} />`

Same as #161
