### ISSUE TITLE
findObjectById no geometry

### ISSUE THREAD

**Issue by qsya** [splinetool/react-spline#146]
spline has geometry，but findObjectById no, how to change shape width?
![image](https://github.com/splinetool/react-spline/assets/19909733/b91a601f-80a9-41d4-a27e-60149c479e2c)
![image](https://github.com/splinetool/react-spline/assets/19909733/c93f0587-439b-4844-b403-fb2421e9b17a)

**Comment by superguigui** [comment]
Hi we currently don't expose ways to change geometries from code. You can instead leverage Spline editor events and trigger then from code for an example (using state or variable changes).

Good luck !
