### ISSUE TITLE
Not working in ios version 14.x.x. 

### ISSUE THREAD

**Issue by rinn-dev** [splinetool/react-spline#156]
I got blank canvas while testing with both react-spline and @splinetool/runtime packages in IOS version 14.x.x of Safari. Actually I tested my spline 3d website using real time browser testing of [lambda test](https://lambdatest.com/) and got some errors in console as shown in the below screenshot.
![image](https://github.com/splinetool/react-spline/assets/66729843/4050cb7e-f73f-4a57-830c-7b2f6890e382).
The spline model that I used and code is the sample one from documentation of react-spline. 

Here is the step to reproduce.
- Open this [sample website](https://spline-react.vercel.app/) in ios 14.x.x Safari.
- You will see it'll be blank page.

[Codesandbox](https://codesandbox.io/p/github/rinn-dev/spline-3d-demo/master?workspaceId=242b5dd1-3411-4307-823d-35fba25cf677)

**Comment by marcofugaro** [comment]
Yes, unfortunately Safari 14 is no longer supported by Spline.
