### ISSUE TITLE
Sponsored issue: Dynamic Text Changes for spline scenes

### ISSUE THREAD

**Issue by dtrejo112** [splinetool/react-spline#157]
I wanted to create a calculator that changes its text based on the calculations done by my react frontend. I do not see a method or way to do this. 

## Priority Support

- @dtrejo112 is using  [Mintycode](https://mintycode.io) to fund this issue.
- If you would like to accept ![amount](https://imageupload.io/ib/zwkd2EaAY6YpPsg_1693209112.png) bounty for solving this issue join [Mintycode](https://mintycode.io/profile?action=CREATOR_SUPPORT_MODAL&requestId=79610c56-9112-421f-8aaf-d5da82a35219&owner=splinetool&name=react-spline).
- Thank you in advance for helping.

[![mintycode](https://imageupload.io/ib/LvxMwrPxam1JW9e_1693210482.png)](https://mintycode.io)

**Comment by hassanxelamin** [comment]
Did you figure this out?

**Comment by superguigui** [comment]
Hi!
There is a way but it has to be done imperatively through the `spline` object returned by the onLoad attribute. The first parameter of the onLoad function is the spline object, and it's an instance of @splinetool/runtime. On this object you will be able to find methods to set and get variables from your spline scene.

More infos about variables:
https://www.npmjs.com/package/@splinetool/runtime#updating-scene-variables
https://www.youtube.com/watch?v=Id_SZVCUVMM

Good luck!
