### ISSUE TITLE
Pass down mouse events from divs with higher z-index

### ISSUE THREAD

**Issue by gandarufu** [splinetool/react-spline#161]
I have a spline element in the background, but the lookAt Event doesn't work if there are divs with mouse events and a higher z index covering it. Is there any way to pass down onMouseMove events to emit the lookAt event?
I have a hover handler on the div and tried both emitting the event from the splineApp object, or the spline object itself, but neither worked.

```
spline.current.emitEvent('lookAt', 'Group');
splineObj.current.emitEvent('lookAt');
```

**Comment by superguigui** [comment]
Hi ! 
Sorry for the late response but you can tell your Spline app to use window for interaction events instead of the canvas itself (default).
```
spline.setGlobalEvents(true);
```
