### ISSUE TITLE
Old Safari and onError message

### ISSUE THREAD

**Issue by SpesEspero** [splinetool/react-spline#162]
Hi guys, thank your for your great tool!

I have few things to discuss:

1) It's not possible to load scene to old version of Safari(<= 14).
<img width="1169" alt="Screenshot 2023-11-21 at 11 27 59" src="https://github.com/splinetool/react-spline/assets/66901537/83f3a629-b271-4a91-add4-4bd351f537c2">

2) Can you add "onError" or "fallback" attribute to the "Spline" component to throw fallback if something goes wrong

**Comment by marcofugaro** [comment]
Yes, unfortunately Safari 14 is no longer supported by Spline.
