### ISSUE TITLE
Expression control

### ISSUE THREAD

**Issue by YenHarvey** [splinetool/react-spline#178]
![image](https://github.com/splinetool/react-spline/assets/48341841/359bc499-47ae-4ce6-89f1-9069dabf66b6)

```javascript
import Spline from '@splinetool/react-spline';
import { useRef } from 'react';

export default function App() {
  const emotion = useRef();

  function handleMouseDown(e) {
    console.log('Mouse down event');
    console.log(e.target.name);

    console.log(emotion.current);
    console.log(emotion.current.name);
  }

  function ClickHandler() {
    // console.log(emotion.current);
    for (const key in emotion.current) {
      console.log(key, emotion.current[key]);
    }

    emotion.current.emitEvent('MouseDown');
  }

  function onLoad(spline) {
    console.log('Scene loaded');
    const obj = spline.findObjectById('f0b03cc5-b9f4-4050-a4d4-45c7e623cb64');
    emotion.current = obj;
  }

  return (
    <>
      <Spline scene="https://prod.spline.design/ogsoXvTGXbAyJ1fr/scene.splinecode"
        onMouseDown={handleMouseDown}
        onLoad={onLoad}
      />

      <button
        type='button'
        onClick={ClickHandler}
      >Show Message
      </button>
    </>
  );
}
```

I want to develop a bot, and I want to control the bot's expression in some way. My current idea is to change different expressions through variables. How should I do it? Can anyone give me a code example? Forgive my incompetence for raising a basic question:(.

**Comment by YevheniiKisel** [comment]
Hello @YenHarvey, that is an "Issues" tab 😅 
Here are should be just bugs and error reports. In some cases - improvements discussion. 
Your question isn't related to any of those topics, so it is irrelevant. 

P.S. I would advice you to start from documentation reading of Spline animation and ReadMe section of react-spline.

**Comment by superguigui** [comment]
Hi You can also go to Spline discord to get help from our community members.

**Comment by YenHarvey** [comment]
这是来自动回复邮件。你好，我将在稍后尽快给你回复。
