### ISSUE TITLE
Version 3.0.3 does not work with React versions prior to 19

### ISSUE THREAD

**Issue by sefakeles** [splinetool/react-spline#186]
First of all, let's take a look at the version history:

- In 3.0.2, versions of peer dependencies `react` and `react-dom` were set to `*` with 5f43b3ab8d0a663ed049ca7f0a1b1cb2bfdba263.
- In 3.0.3, versions of dev dependencies `react` and `react-dom` were set to `19.0.0-rc-f994737d14-20240522` with 9c9247182af7728a94604194d4cf37cce3bff0f5.

Just because `@vitejs/plugin-react` uses React's new JSX transform by default, it bundles `react/jsx-runtime` and `react/jsx-dev-runtime` with the original Spline code. This causes Spline 3.0.3 not to work with React versions prior to 19, despite peer dependency versions being `*`. 

I think the solution to this problem might be using one of the following configs for Vite depending on the desired output. What do you think?

```javascript
export default defineConfig({
  plugins: [react()],
  optimizeDeps: {
    exclude: ['react/jsx-runtime', 'react/jsx-dev-runtime'],
  },
});
```

```javascript
export default defineConfig({
  plugins: [react({ jsxRuntime: 'classic' })],
});
```

**Comment by marcofugaro** [comment]
Should be solved now, can you check?

**Comment by sefakeles** [comment]
Solved. Thanks.
