### ISSUE TITLE
Unable to Update Image Variable in Spline Scene with React Integration

### ISSUE THREAD

**Issue by realitydesigners** [splinetool/react-spline#196]
**Description:**

I'm encountering an issue with updating the `Image` variable in a Spline scene when using the `@splinetool/react-spline` package. Despite correctly setting the variable, the image does not appear to update as expected.

**Steps to Reproduce:**

1. Set up a Spline scene with an object named `TeamImage` that has a material expecting an image texture.
2. Export the Spline scene and integrate it into a React project using `@splinetool/react-spline`.
3. Attempt to update the image texture using the following code:

```javascript
import Spline from '@splinetool/react-spline';
import { useEffect, useRef } from 'react';
import * as THREE from 'three'; // Importing THREE

const SplineScene = ({ sceneUrl }) => {
  const splineRef = useRef(null);

  const onLoad = (spline) => {
    splineRef.current = spline;
    const imageObject = spline.findObjectByName('TeamImage');
    const imageUrl = 'https://example.com/path/to/your/image.png'; // Replace with any CDN image URL
    const imageId = 100; // Assuming a numerical ID is required
    
    // Updating image variable
    if (imageObject) {
      spline.setVariable('TeamImage', imageId);
      const img = new Image();
      img.src = imageUrl;
      img.crossOrigin = 'anonymous';
      img.onload = () => {
        if (imageObject.material) {
          const texture = new THREE.Texture(img);
          texture.needsUpdate = true;
          imageObject.material.map = texture;
          imageObject.material.needsUpdate = true;
          console.log('Image texture updated:', imageUrl);
        } else {
          console.error('imageObject.material is undefined');
        }
      };
    } else {
      console.log('TeamImage object not found');
    }
  };

  useEffect(() => {
    if (splineRef.current) {
      const spline = splineRef.current;
      const imageObject = spline.findObjectByName('TeamImage');
      if (imageObject) {
        const imageUrl = 'https://example.com/path/to/your/image.png'; // Replace with any CDN image URL
        const img = new Image();
        img.src = imageUrl;
        img.crossOrigin = 'anonymous';
        img.onload = () => {
          if (imageObject.material) {
            const texture = new THREE.Texture(img);
            texture.needsUpdate = true;
            imageObject.material.map = texture;
            imageObject.material.needsUpdate = true;
            console.log('Image texture updated:', imageUrl);
          } else {
            console.error('imageObject.material is undefined');
          }
        };
      } else {
        console.log('TeamImage object not found');
      }
    }
  }, []);

  return (
    <Spline scene={sceneUrl} onLoad={onLoad} />
  );
};

export default SplineScene;
```

**Expected Behavior:**
The image texture should update correctly on the `TeamImage` object when the variable is set and the texture is loaded.

**Actual Behavior:**
The image texture does not update, and the material property of the object remains undefined.

**Console Output:**
```plaintext
Spline object loaded: wN {_viewportMode: 1, _viewportWidth: 484, _viewportHeight: 597, ...}
TeamName: Proxy(Object) {name: 'TeamName', uuid: '0058b55a-193a-452c-ab2b-03a094ebce46', ...}
TeamImage: Proxy(Object) {name: 'TeamImage', uuid: 'db0c6969-8af7-40a9-bfc8-c39f8ce68970', ...}
Image ID: 100
Setting TeamImage variable to: 100
imageObject.material is undefined
```

**Environment:**
- React version: 18.2.0
- `@splinetool/react-spline` version: latest
- Three.js version: latest

**Additional Context:**
The Spline scene object appears to load correctly, and other variables (e.g., `TeamName`) update as expected. The issue seems to be isolated to updating image textures on objects.

**Steps Taken:**
- Verified the `TeamImage` object in the Spline editor is set to accept image textures.
- Confirmed the variable type for `TeamImage` in Spline is numerical.
- Used detailed logging to track the state and properties of the `TeamImage` object.

**Request:**
Please provide guidance on how to correctly update the image texture for an object in a Spline scene when integrated with a React project.

**Comment by bilalalbkre** [comment]
Hi @realitydesigners I was wondering did you find any way to be able to change the image through the code ?

**Comment by realitydesigners** [comment]
> Hi @realitydesigners I was wondering did you find any way to be able to change the image through the code ?  
> 
> 

Unfortunately it is not possible at the moment.
