### ISSUE TITLE
[Fix] Can't resize Spline scene.

### ISSUE THREAD

**Issue by Walidoux** [splinetool/react-spline#31]
As the title says, it's actually impossible but possible with a workaround here. #26 
I tried that down below in the video but this is definitely not the result we want. 😓
> The canvas size reverts to full viewport width/height as soon as the viewport is slightly resized.

Here's what it actually renders:

https://user-images.githubusercontent.com/87608619/163722776-e7c509d1-f99e-4567-b49c-f92bb6d11396.mov

**Comment by marcofugaro** [comment]
Did you set your frame size to fullscreen?

<img width="240" alt="image" src="https://user-images.githubusercontent.com/7217420/163970205-30ae1ceb-6b68-4584-865f-b0e6de5612ae.png">

**Comment by Walidoux** [comment]
> Did you set your frame size to fullscreen?
> 
> <img alt="image" width="240" src="https://user-images.githubusercontent.com/7217420/163970205-30ae1ceb-6b68-4584-865f-b0e6de5612ae.png">

Can't find this category in the application

**Comment by marcofugaro** [comment]
It's on the right sidebar when you have nothing selected

**Comment by Walidoux** [comment]
Oh okay, I got it, problem solved thanks, appreciate this @marcofugaro 👌

**Comment by michaeljblum** [comment]
Have you managed responsive sizing @Walidoux? I unchecked full screen, opted for custom size, but it's statically stuck at those set dimensions. 

I'd love to be able to more flexibly interface with Spline in React, if only for how easy/awesome it is to make things quickly in the app and also how effortless it is to animate harder to animate things like depth gradient materials in React via Spline.

**Comment by Walidoux** [comment]
> Have you managed responsive sizing @Walidoux? I unchecked full screen, opted for custom size, but it's statically stuck at those set dimensions. 
> 
> 
> 
> I'd love to be able to more flexibly interface with Spline in React, if only for how easy/awesome it is to make things quickly in the app and also how effortless it is to animate harder to animate things like depth gradient materials in React via Spline.

Didn't try that, you would prefer creating an issue as PR for that for more flexibility, I agree that we can't control several functionalities albeit is it still possible in the application but it's clearly annoying when it comes to making small changes.
I will contribute for a PR if necessary. @michaeljblum

**Comment by marcofugaro** [comment]
The `Full Screen` preset has been renamed to `Responsive`, and it now adapts to the parent dimensions!

**Comment by marcofugaro** [comment]
@michaeljblum you can just use a generic `useRaf` hook

https://github.com/streamich/react-use/blob/master/docs/useRaf.md
