### ISSUE TITLE
How to disable scroll and drag action ?

### ISSUE THREAD

**Issue by lmcmz** [splinetool/react-spline#33]
Currently, I added the `Look at` animation to this object. 
But is there any way I could disable drag and scroll for the canvas ?

| after scroll  | normal|
|--|--|
|![Screen Shot 2022-04-21 at 11 52 41 pm](https://user-images.githubusercontent.com/9669733/164473129-b57ff87f-7e44-4b7b-8ca9-596d83a65aa4.png)|![Screen Shot 2022-04-21 at 11 52 33 pm](https://user-images.githubusercontent.com/9669733/164473151-b6fbd78e-459b-4a42-be8c-e5d5ad35eaf4.png)|

Scene URL:
https://draft.spline.design/RMyQa1DNsSpdREER/scene.spline

**Comment by marcofugaro** [comment]
The options you're looking for are relatively `Orbit` and `Page Scroll` in the Play Settings: 

<img width="356" alt="image" src="https://user-images.githubusercontent.com/7217420/164477715-b52199d9-5afd-44e3-b026-9cda8ea884b9.png">

**Comment by lmcmz** [comment]
Thanks a lot !! Problem resolved 👍
