### ISSUE TITLE
Text does not show up in react-exported scene

### ISSUE THREAD

**Issue by mcgingras** [splinetool/react-spline#37]
I have a small demo-scene with a text object. When I export to a public spline URL the text shows up fine, but in the react export, the text is nowhere to be found -- it just doesn't show up at all.

Here is a screenshot of the react version loaded up, and a link to the public url. 
<img width="1838" alt="Screen Shot 2022-05-08 at 3 40 26 PM" src="https://user-images.githubusercontent.com/12549482/167316912-30088687-9f0e-4f9b-83c8-851749538fe9.png">

https://my.spline.design/textdemo-bbbf3445a6772bbe794cfc31c26f89f1/

**Comment by marcofugaro** [comment]
Fixed in latest version! Please re-export your scene.
