### ISSUE TITLE
Is it possible to host the .splinecode file locally … within the react app ? 

### ISSUE THREAD

**Issue by mainframeai** [splinetool/react-spline#52]
I have tried it of course, however it did not work out. The console reported, that no end of buffer was found. 

Is there any known solution for it  ? I have exported a small scene in react format just to see if this is possible. 
(as this is possibly a deal-breaker for some of our clients… Corporate compliance and GDPR issues.)

**Comment by marcofugaro** [comment]
Yes it is possible. You have to put the `.splinecode` file in the `public` folder and use an absolute path.

**Comment by mainframeai** [comment]
AWESOME News!!!! Thanks a lot! I will try today. :) (I am so relieved, since I love the tool… If this works out … Pro membership is coming quickly) 🥇 Thanks a lot for the superquick response.

**Comment by mainframeai** [comment]
This is solved! One Member more! :) #greatstuff This worked flawlessly!
