### ISSUE TITLE
Next.Js Support

### ISSUE THREAD

**Issue by SilasNiewierra** [splinetool/react-spline#53]
Hi there,

I love Spline and would like to use it in my Next.js app.
However, if I follow the instructions of a basic Next.js setup and react-spline setup, I get an error.

**Steps to Reproduce:**
1. Create Next.js App: `npx create-next-app@latest`
2. Install react-spline: `npm install @splinetool/react-spline @splinetool/runtime`
3. Replace content in index.js with: 
```
import Spline from '@splinetool/react-spline';

export default function App() {
  return (
    <div>
      <Spline scene="https://prod.spline.design/6Wq1Q7YGyM-iab9i/scene.splinecode" />
    </div>
  );
}
```
4. Run the app: `npm run dev`

**Expected Result:**
Seeing the default spline animation

**Actual Result:**
```
SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/silasniewierra/Documents/Coding/test/test-spline/node_modules/@splinetool/react-spline/dist/react-spline.cjs.js:1:546)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10) {
  page: '/'
}
Warning: data for page "/_error" is 430 kB which exceeds the threshold of 128 kB, this amount of data can reduce performance.
```

<img width="976" alt="Bildschirmfoto 2022-07-01 um 17 02 32" src="https://user-images.githubusercontent.com/55000832/176920122-d958e64d-e15c-4b14-b968-9b3e0efb4c3a.png">

! Even if I don't use the `<Spline>` component and just import it on the top, the error appears.

**Comment by ivanburlakov** [comment]
Hello! Spline works in my Next.js app. Do not replace the whole index.js file. Insert the import line and add `<Spline>` tag to tone of your page files or in `_app.js` file.

**Comment by SilasNiewierra** [comment]
Did you set it up with the most recent next.js setup?
I think it has to do something with the dependencies of react 16 and 17, but Next.js is on react 18.
I actually didn't replace the whole index.js file. That was just to demonstrate the problem 😄 
I doesn't work either way, however: When I start my app with spline commented out and then after the app is running, comment it back in, it does work. But as soon as I make a page reload the error is back.

**Comment by ivanburlakov** [comment]
@SilasNiewierra yes, I am using it in newly created `create-next-app` with `React` version `18.1.0`. Strange error however.. Maybe try it on absolutely new empty app? It needs to be said, that this module is quite raw currently and I ran in some bugs too. Hopefully it will continue to develop 😊

**Comment by SilasNiewierra** [comment]
Hi @ivanburlakov.
I just created a completely new next app with `npx create-next-app`.
Afterwards I installed spline `npm install @splinetool/react-spline @splinetool/runtime` and created a new component `Spline.jsx` with the default code:
```
import Spline from '@splinetool/react-spline';

export default function App() {
  return (
    <div>
      <Spline scene="https://prod.spline.design/6Wq1Q7YGyM-iab9i/scene.splinecode" />
    </div>
  );
}
```
Then I used my Spline component in the default index.js.
Still, the same exact error occurs.

With this warning coming right before the error:
```
Warning: data for page "/_error" is 430 kB which exceeds the threshold of 128 kB, this amount of data can reduce performance.
See more info here: https://nextjs.org/docs/messages/large-page-data

```

You said it worked on your end. Could you tell me what you did and maybe provide a little repo or describe your process?

**Comment by ivanburlakov** [comment]
@SilasNiewierra I created a working blank project and uploaded it to this repo - https://github.com/ivanburlakov/spline-nextjs-example . Next.js App code structure is a bit different from React.

**Comment by SilasNiewierra** [comment]
@ivanburlakov 
Finally I was able to fix it. 
The problem was.... my node version was v12 🙈 
I changed it to v17 and everything runs smooth like butter.

I figured it out, because I used your repo and tried yarn as well, but I got the exact same error. So I knew it had to be on my system 😄 

Thank you so much for your help 🙌

**Comment by Heavy108** [comment]
Hi everyone,
does any one know how to fix this
[Violation] Added non-passive event listener to a scroll-blocking 'wheel' event. Consider marking event handler as 'passive' to make the page more responsive

using this spline https://prod.spline.design/YAUqXqFXE65T0axd/scene.splinecode
