### ISSUE TITLE
Issue on generation and import

### ISSUE THREAD

**Issue by VirAlex** [splinetool/react-spline#55]
Hello, I tried to do this 'tuto', everything works fine as you can see here: [Spline](https://my.spline.design/untitled-c5ab3ae34bb1ce72fce1b0c59a004127/), but when I try to import it for react I haven't got my Blob, [CodeSandbox](https://codesandbox.io/s/splite-tuto-forked-sjjqez), but it works fine with Vanilla JS for example. [Vanilla](https://codesandbox.io/s/splite-tuto-forked-y61rzy).
I tried to on local with create vite react app.
🙏 Thank you

**Comment by marcofugaro** [comment]
Your codesandbox is showing correctly for me.

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/7217420/177567447-ab701461-2d7e-49fb-a295-55bf2e40f68d.png">

**Comment by marcofugaro** [comment]
Hmm could you restart the app and export again?

**Comment by marcofugaro** [comment]
Issue should be fixed now
