### ISSUE TITLE
about the init size

### ISSUE THREAD

**Issue by flashoop** [splinetool/react-spline#56]
The size of the model made in spline is 100x100x100 by default, but the default size of mesh in r3f is 1x1x1, which requires manual scaling after loading, which is very inconvenient. It is recommended to modify this problem

**Comment by marcofugaro** [comment]
Spline uses a 100x increment internally, meaning that each Spline unit corresponds to a pixel on screen.
In three.js instead each unit corresponds to 1 physical meter.
