### ISSUE TITLE
`TypeError: Cannot set property value of #<Eu> which has only a getter`

### ISSUE THREAD

**Issue by Suvraneel** [splinetool/react-spline#57]
![image](https://user-images.githubusercontent.com/63473496/178412623-640d7520-7ea3-46d1-a17c-535e90c31a03.png)

This error keeps popping up, possibly after I added the blob.
Configuration:  NextJS, TailwindCSS
"next": "12.2.0",
"react": "18.2.0"

Steps to reproduce: 
It works fine on the sandbox [here](https://qyre1d.csb.app/) , 
But since the sandbox uses uses many deprecated libraries, might be an compatibility issue with newer environments.

CC:  @marcofugaro
-Thanks

**Comment by marcofugaro** [comment]
You said you're using NextJS. Could you share a codesandbox of the error with NextJS? The one you shared uses just plain react.

**Comment by Suvraneel** [comment]
@marcofugaro  Hey Marco, really thankful to your speedy reply.
The error went away after I let go of that spline design & recreated blobs & polygons...
That most likely was a buggy `.splinecode` file throwing error on State change Events....

Anyway, its working super-fine now in my Next.js environment [here](https://suvraneel-folio.vercel.app/).
Closing this issue & apologies for the bother. :octocat:
