### ISSUE TITLE
How to use a local  scene file?

### ISSUE THREAD

**Issue by leeumm** [splinetool/react-spline#59]
In webpack, is a “spline-loader” dependency package required?
I found [@splinetool/loader](https://www.npmjs.com/package/@splinetool/loader) and [pyz-spline-loader](https://www.npmjs.com/package/pyz-spline-loader), but it doesn't work

**Comment by leeumm** [comment]
> In webpack, is a “spline-loader” dependency package required? I found [@splinetool/loader](https://www.npmjs.com/package/@splinetool/loader) and [pyz-spline-loader](https://www.npmjs.com/package/pyz-spline-loader), but it doesn't work

Sorry for the misunderstanding 😬, just put a reference to the root directory

**Comment by marcofugaro** [comment]
For react-spline, only the `@splinetool/runtime` package is needed, check out the [Installation](https://github.com/splinetool/react-spline#install) section of the README.
