### ISSUE TITLE
For @splinetool/runtime: Cannot conver undedind or null to object

### ISSUE THREAD

**Issue by rllxxx** [splinetool/react-spline#62]
environment:  
node 14
vite 2.8.6
react 16.8
@splinetool/runtime  >= 0.9.76

![image](https://user-images.githubusercontent.com/13895891/179702690-15f777cd-4b3c-4c1c-9869-73c59f9f937b.png)

![image](https://user-images.githubusercontent.com/13895891/179702710-2d144cba-e0a3-4e52-8757-e1ac235d5ff2.png)

Can you guys provide some help with these? 
Thank you very much~

**Comment by marcofugaro** [comment]
Fixed in `@splinetool/runtime` version `0.9.82`
