### ISSUE TITLE
Spline does not work with Next JS

### ISSUE THREAD

**Issue by Singh-Avi** [splinetool/react-spline#63]
Spline is marketed to work with React Js out of the box but it does not work with NextJs unfortunately. 

import React from "react";
import Spline from "@splinetool/react-spline";

export default function BgComponent() {
  return (
    <>
      <Spline scene="https://prod.spline.design/rrdZLil0oLkQVd2N/scene.splinecode" />
    </>
  );
}

using this code in a next js page always results in reference error - Image not defined. 
![image](https://user-images.githubusercontent.com/19604559/180193178-af5a8cd3-1d12-4751-b788-55ce432461c1.png)

**Comment by marcofugaro** [comment]
Will be fixed in the next release of `@splinetool/runtime`

**Comment by marcofugaro** [comment]
Fixed in `@splinetool/runtime` version `0.9.82`
