### ISSUE TITLE
React Native Support ?

### ISSUE THREAD

**Issue by Suvraneel** [splinetool/react-spline#66]
Is this under development or shipped already or not planned?
If shipped, an example would be noiceee 🔥  

Couldn't infer the status from #39

**Comment by marcofugaro** [comment]
Hi, react-spline should be working already with React Native, do you have any issues while trying to use it? 🙂

**Comment by Suvraneel** [comment]
I haven't yet. Just was asking around before I tried it out, since I didn't see its usage examples anywhere.
And this makes me very happy. Now Imma transform my apps to more awesome ones. 🔥 

Thanks @marcofugaro . 
PS -  Your CodePen creations are **fire** btw.   :octocat:

**Comment by matthewcarlreetz** [comment]
ok, yes, this is what I was seeing as well, I had to polyfill canvas and window.

**Comment by arlindiDev** [comment]
@matthewcarlreetz were you able to get spline working on your react native app?
