### ISSUE TITLE
Some models blocked by CORS

### ISSUE THREAD

**Issue by ryans1224** [splinetool/react-spline#70]
Example: https://codesandbox.io/s/3d-camera-forked-cg06zu?file=/src/App.js

The example above shows 2 models, the first works fine.

The latter spline component (the one uncommented) gives a failed to fetch response because of CORS. (see the console)

Let me know if anything else is needed in this issue, would love to be able to use the react Spline component in my project!

**Comment by marcofugaro** [comment]
The codesandbox seems to work just fine

<img width="1119" alt="image" src="https://user-images.githubusercontent.com/7217420/184104325-9571952b-73be-43ad-bbb6-1151f607e901.png">

https://codesandbox.io/s/3d-camera-forked-qbb97r?file=/src/App.js

**Comment by ryans1224** [comment]
Huh, the old it works on my machine but not on yours, very strange! It's an issue with CORS that only applies to the the second component spline URL.

This is what i get only for the second spline component:

<img width="788" alt="Screenshot 2022-08-11 at 11 41 54" src="https://user-images.githubusercontent.com/7398104/184116735-0052bdbc-63c0-414c-909c-448e10ff774e.png">

A reason why you are not able to reproduce may be if you have disabled web security in whatever browser you are using.

Are you able to help any further?

**Comment by marcofugaro** [comment]
That error doesn't seem familiar, the issue is on your side I believe. I can't help you with that.

**Comment by ryans1224** [comment]
Sorry to keep coming back, but have you tried to replicate at all on other machines / different browsers? In my efforts I have tried on 2 machines, my phone, and multiple browser combos, all in which this is replica-table. So it is not just an issue on my side.

As stated above, I can access fine if i start chrome with the `--disable-web-security` flag. My guess would be you have this flag set by default on chrome, or similar on whatever browser you are using, hence the error is not visible. 

Not pushing for an immediate fix or anything, just want the issue to be acknowledged.

**Comment by vivekascoder** [comment]
You can just export the model as .splinecode and it should work fine.

**Comment by marcofugaro** [comment]
We can't reproduce this issue on our machines, can't really help you.

But yes, you can always download the `.splinecode` by visiting the URL (https://prod.spline.design/JMwGuOuABb5gBWR1/scene.splinecode) and hosting it yourself

**Comment by ryans1224** [comment]
I still get it from time to time with newer spline projects... Its an intermittent problem which is not just related to one user's setup, and as such should be reopened

**Comment by m3h0w** [comment]
Got the same problem
