### ISSUE TITLE
CORS: Unhandled Runtime Error

### ISSUE THREAD

**Issue by mattsince87** [splinetool/react-spline#87]
Hey, i'm developing a site locally on `localhost:3000` and I'm receiving the following error ion console:

```
Access to fetch at 'https://prod.spline.design/PVMoc332wUkkwrCV/scene.splinecode' from origin 'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

I've taken a look at the docs but can't see anything that suggests i cant put this into my project locally ?

```js
import Spline from '@splinetool/react-spline';

export default function App() {
  return (
    <Spline scene="https://prod.spline.design/PVMoc332wUkkwrCV/scene.splinecode" />
  );
}
```

**Comment by edwindharris** [comment]
I tested your .splinecode link in my [react <> spline template](https://github.com/edwindharris/spline.design-react-trigger) and the console returned the same error as you are receiving. The link in my project does not throw the error. I know this doesn't help, but might support any processes of elimination at your end.

Duplicating and re-exporting a scene in Spline app generates a new link / fresh export... I try this when I get stuck , it sometimes solves mysterious goings-on.

**Comment by mattsince87** [comment]
Ah that’s good to know, will give it a try and update if it works - thank you

**Comment by xodms0309** [comment]
I'm having the same issue :< It was working fine, but suddenly receiving CORS error randomly. sometimes it works, sometimes it doesn't. I would like to get an update about this issue if there's a solution.

**Comment by mattsince87** [comment]
> I tested your .splinecode link in my [react <> spline template](https://github.com/edwindharris/spline.design-react-trigger) locally, and the console returned the same error as you are receiving. The link in my project does not throw the error. I know this doesn't help, but might support any processes of elimination at your end.
> 
> Duplicating and re-exporting a scene in Spline app generates a new link / fresh export... I try this when I get stuck , it sometimes solves mysterious goings-on.

@edwindharris This fixed the issue thanks mate
