### ISSUE TITLE
Does Spline work with Next.js and Typescript?

### ISSUE THREAD

**Issue by SmgTR** [splinetool/react-spline#93]
Hi, does Spline work with next ts? 
Spline loads normally on dev, but when I start app build, I'm getting errors:
``` Application error: a client-side exception has occurred (see the browser console for more information).```
And in console errors:
```TypeError: Super constructor null of anonymous class is not a constructor```
```Uncaught Error: Minified React error #418 "Hydration failed because the initial UI does not match what was rendered on the server."```
```Uncaught Error: Minified React error #423 "There was an error while hydrating. Because the error happened outside of a Suspense boundary, the entire root will switch to client rendering"```

I tried to use dynamic import from next with suspense, ssr option set as false and both does not work in this case.
I also tried it in minified app with next app create, but I got the same error after build start.

**Comment by eskimm** [comment]
Ive got the same issues, build version fails once loaded in browser without Typescript.

**Comment by G4den** [comment]
Im having the same issue

**Comment by marcofugaro** [comment]
Fixed in `@splinetool/runtime` version `0.9.145`
