### ISSUE TITLE
Hydration failed because the initial UI does not match what was rendered on the server

### ISSUE THREAD

**Issue by steven-tey** [splinetool/react-spline#94]
Running into a super odd bug with React 18 & Next.js 13

![CleanShot 2022-11-27 at 16 22 44](https://user-images.githubusercontent.com/28986134/204164965-d314f2a1-d6ec-4c0c-b0da-85aa32f25912.png)

I suspect it's related to the infamous `Hydration failed because the initial UI does not match what was rendered on the server.` error: https://github.com/vercel/next.js/discussions/35773

However, even when I tried dynamically importing the Spline component with `next/dynamic` and workarounds like [this](https://github.com/vercel/next.js/discussions/35773#discussioncomment-2485078), the problem still persisted.

I'm at a complete loss and had to [remove the Spline component temporarily](https://github.com/steven-tey/dub/blob/main/pages/app/welcome.tsx#L46-L52) to not break my app 😓 

Would love some help debugging this. Here's my code: https://github.com/steven-tey/dub/blob/main/components/app/welcome/intro.tsx#L33-L37

**Comment by marcofugaro** [comment]
This happens in the `next start`, right?

**Comment by steven-tey** [comment]
yup @marcofugaro

**Comment by marcofugaro** [comment]
Fixed in `@splinetool/runtime` version `0.9.145`

**Comment by steven-tey** [comment]
It [works](https://github.com/steven-tey/dub/commit/a9ad3bcba6c1d04baba36d13a06905418670a71a)!! Thank you so much for fixing this!
