### ISSUE TITLE
How can I fix React Export code error?

### ISSUE THREAD

**Issue by dicekymt** [splinetool/react-spline#98]
I embed the code output by React in Astro and build it, I occur the following error.

> (node:85185) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
> (Use `node --trace-warnings ...` to show where the warning was created)
> /Users/dicek/Dev/my-portfolio/node_modules/.pnpm/@splinetool+react-spline@2.2.3_ujkxyqf34oujlqwdyujhezpoym/node_modules/@splinetool/react-spline/dist/react-spline.es.js:29
> import require$$0, { forwardRef, useRef, useState, useEffect } from "react";

**Comment by marcofugaro** [comment]
This is an issue with Astro, please post the issue in their repo.
